# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

similarity_mat <- function(cluster_record) {
    .Call(`_BayesicGibbs_similarity_mat`, cluster_record)
}

entropy <- function(class_weights) {
    .Call(`_BayesicGibbs_entropy`, class_weights)
}

dirichlet_posterior <- function(concentration_0, cluster_labels, num_clusters) {
    .Call(`_BayesicGibbs_dirichlet_posterior`, concentration_0, cluster_labels, num_clusters)
}

cat_counter <- function(data) {
    .Call(`_BayesicGibbs_cat_counter`, data)
}

categorical_clustering <- function(data, phi_prior, cluster_labels, fix_vec, cluster_weight_priors, num_clusters, num_iter, burn, thinning) {
    .Call(`_BayesicGibbs_categorical_clustering`, data, phi_prior, cluster_labels, fix_vec, cluster_weight_priors, num_clusters, num_iter, burn, thinning)
}

gaussian_clustering <- function(num_iter, concentration_0, scale_0, class_labels, fix_vec, mu_0, lambda_0, data, df_0, k, burn, thinning, outlier = FALSE, t_df = 4.0, record_posteriors = FALSE, normalise = FALSE) {
    .Call(`_BayesicGibbs_gaussian_clustering`, num_iter, concentration_0, scale_0, class_labels, fix_vec, mu_0, lambda_0, data, df_0, k, burn, thinning, outlier, t_df, record_posteriors, normalise)
}

mdi <- function(gaussian_data, categorical_data, mu_0, lambda_0, scale_0, df_0, cluster_weight_priors_gaussian, cluster_weight_priors_categorical, phi_prior, cluster_labels_gaussian, cluster_labels_categorical, num_clusters_gaussian, num_clusters_categorical, fix_vec, num_iter, burn, thinning, outlier = FALSE, t_df = 4.0, record_posteriors = FALSE, normalise = FALSE) {
    .Call(`_BayesicGibbs_mdi`, gaussian_data, categorical_data, mu_0, lambda_0, scale_0, df_0, cluster_weight_priors_gaussian, cluster_weight_priors_categorical, phi_prior, cluster_labels_gaussian, cluster_labels_categorical, num_clusters_gaussian, num_clusters_categorical, fix_vec, num_iter, burn, thinning, outlier, t_df, record_posteriors, normalise)
}

rcpparma_hello_world <- function() {
    .Call(`_BayesicGibbs_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_BayesicGibbs_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_BayesicGibbs_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_BayesicGibbs_rcpparma_bothproducts`, x)
}

